version: "3"
services:
  familyapp:
    build:
      context: ./FamilyApp
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - 9000:8080
      
      
  familymemberapp:
    build:
      context: ./FamilyMemberApp
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - 9100:8080
      
  flyway:
    image: flyway/flyway
    command: -url=jdbc:postgresql://postgres:5432/FamilyDB -user=postgres -password=janekcep -connectRetries=60 migrate
    volumes:
      - .:/flyway/sql
    depends_on:
      - db
      
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=janekcep
      - POSTGRES_DB=FamilyDB
    ports:
      - '5432:5432'
